import { prisma } from "@/lib/prisma";

type SpeciesRow = {
  id: number;
  speciesName: string; // scientific name (matches Excel 'species' column)
  germanName: string;
  latinName: string;
  family: string;
};

const SPECIES: SpeciesRow[] = [
  {
    id: 1,
    speciesName: "Abramis brama",
    germanName: "Brachse",
    latinName: "Abramis brama",
    family: "Cyprinidae",
  },
  {
    id: 2,
    speciesName: "Abramis brama hybrid",
    germanName: "Brachsen-Hybrid",
    latinName: "Abramis brama hybrid",
    family: "Cyprinidae",
  },
  {
    id: 3,
    speciesName: "Acipenser baerii",
    germanName: "Sibirischer Stör",
    latinName: "Acipenser baerii",
    family: "Acipenseridae",
  },
  {
    id: 4,
    speciesName: "Acipenser gueldenstaedtii",
    germanName: "Waxdick-Stör",
    latinName: "Acipenser gueldenstaedtii",
    family: "Acipenseridae",
  },
  {
    id: 5,
    speciesName: "Acipenser hybrid",
    germanName: "Stör-Hybrid",
    latinName: "Acipenser hybrid",
    family: "Acipenseridae",
  },
  {
    id: 6,
    speciesName: "Acipenser ruthenus",
    germanName: "Sterlet",
    latinName: "Acipenser ruthenus",
    family: "Acipenseridae",
  },
  {
    id: 7,
    speciesName: "Acipenser stellatus",
    germanName: "Sternhausen",
    latinName: "Acipenser stellatus",
    family: "Acipenseridae",
  },
  {
    id: 8,
    speciesName: "Alburnoides bipunctatus",
    germanName: "Schneider",
    latinName: "Alburnoides bipunctatus",
    family: "Cyprinidae",
  },
  {
    id: 9,
    speciesName: "Alburnus alburnus",
    germanName: "Ukelei",
    latinName: "Alburnus alburnus",
    family: "Cyprinidae",
  },
  {
    id: 10,
    speciesName: "Alburnus mento",
    germanName: "Seelaube",
    latinName: "Alburnus mento",
    family: "Cyprinidae",
  },
  {
    id: 11,
    speciesName: "Ameiurus melas",
    germanName: "Schwarzer Zwergwels",
    latinName: "Ameiurus melas",
    family: "Ictaluridae",
  },
  {
    id: 12,
    speciesName: "Ameiurus nebulosus",
    germanName: "Brauner Zwergwels",
    latinName: "Ameiurus nebulosus",
    family: "Ictaluridae",
  },
  {
    id: 13,
    speciesName: "Ameiurus sp.",
    germanName: "Zwergwels sp.",
    latinName: "Ameiurus sp.",
    family: "Ictaluridae",
  },
  {
    id: 14,
    speciesName: "Anguilla anguilla",
    germanName: "Aal",
    latinName: "Anguilla anguilla",
    family: "Anguillidae",
  },
  {
    id: 15,
    speciesName: "Aspius aspius hybrid",
    germanName: "Schied-Hybrid",
    latinName: "Aspius aspius hybrid",
    family: "Cyprinidae",
  },
  {
    id: 16,
    speciesName: "Aspius aspius x Leuciscus idus",
    germanName: "Schied x Aland",
    latinName: "Aspius aspius x Leuciscus idus",
    family: "Cyprinidae",
  },
  {
    id: 17,
    speciesName: "Babka gymnotrachelus",
    germanName: "Kesslergrundel",
    latinName: "Babka gymnotrachelus",
    family: "Gobiidae",
  },
  {
    id: 18,
    speciesName: "Ballerus ballerus",
    germanName: "Zope",
    latinName: "Ballerus ballerus",
    family: "Cyprinidae",
  },
  {
    id: 19,
    speciesName: "Ballerus sapa",
    germanName: "Zobel",
    latinName: "Ballerus sapa",
    family: "Cyprinidae",
  },
  {
    id: 20,
    speciesName: "Ballerus sp.",
    germanName: "Ballerus sp.",
    latinName: "Ballerus sp.",
    family: "Cyprinidae",
  },
  {
    id: 21,
    speciesName: "Barbatula barbatula",
    germanName: "Bachschmerle",
    latinName: "Barbatula barbatula",
    family: "Nemacheilidae",
  },
  {
    id: 22,
    speciesName: "Barbus balcanicus",
    germanName: "Balkanbarbe",
    latinName: "Barbus balcanicus",
    family: "Cyprinidae",
  },
  {
    id: 23,
    speciesName: "Barbus barbus",
    germanName: "Barbe",
    latinName: "Barbus barbus",
    family: "Cyprinidae",
  },
  {
    id: 24,
    speciesName: "Blicca bjoerkna",
    germanName: "Güster",
    latinName: "Blicca bjoerkna",
    family: "Cyprinidae",
  },
  {
    id: 25,
    speciesName: "Carassius auratus",
    germanName: "Goldfisch",
    latinName: "Carassius auratus",
    family: "Cyprinidae",
  },
  {
    id: 26,
    speciesName: "Carassius carassius",
    germanName: "Karausche",
    latinName: "Carassius carassius",
    family: "Cyprinidae",
  },
  {
    id: 27,
    speciesName: "Carassius gibelio",
    germanName: "Silberkarausche",
    latinName: "Carassius gibelio",
    family: "Cyprinidae",
  },
  {
    id: 28,
    speciesName: "Carassius gibelio x Blicca bjoerkna",
    germanName: "Silberkarausche x Güster",
    latinName: "Carassius gibelio x Blicca bjoerkna",
    family: "Cyprinidae",
  },
  {
    id: 29,
    speciesName: "Carassius Hybrid",
    germanName: "Karauschen-Hybrid",
    latinName: "Carassius Hybrid",
    family: "Cyprinidae",
  },
  {
    id: 30,
    speciesName: "Carassius sp.",
    germanName: "Karausche sp.",
    latinName: "Carassius sp.",
    family: "Cyprinidae",
  },
  {
    id: 31,
    speciesName: "Chondrostoma nasus",
    germanName: "Nase",
    latinName: "Chondrostoma nasus",
    family: "Cyprinidae",
  },
  {
    id: 32,
    speciesName: "Chondrostoma nasus x Rutilus rutilus",
    germanName: "Nase x Rotauge",
    latinName: "Chondrostoma nasus x Rutilus rutilus",
    family: "Cyprinidae",
  },
  {
    id: 33,
    speciesName: "Cobitis elongatoides",
    germanName: "Donausteinbeißer",
    latinName: "Cobitis elongatoides",
    family: "Cobitidae",
  },
  {
    id: 34,
    speciesName: "Coregonus sp.",
    germanName: "Renke sp.",
    latinName: "Coregonus sp.",
    family: "Salmonidae",
  },
  {
    id: 35,
    speciesName: "Cottus gobio",
    germanName: "Groppe (Mühlkoppe)",
    latinName: "Cottus gobio",
    family: "Cottidae",
  },
  {
    id: 36,
    speciesName: "Ctenopharyngodon idella",
    germanName: "Graskarpfen",
    latinName: "Ctenopharyngodon idella",
    family: "Cyprinidae",
  },
  {
    id: 37,
    speciesName: "Cyprinidae",
    germanName: "Karpfenfisch",
    latinName: "Cyprinidae",
    family: "Cyprinidae",
  },
  {
    id: 38,
    speciesName: "Cyprinidae hybrid",
    germanName: "Karpfenfisch-Hybrid",
    latinName: "Cyprinidae hybrid",
    family: "Cyprinidae",
  },
  {
    id: 39,
    speciesName: "Cyprinus carpio",
    germanName: "Karpfen",
    latinName: "Cyprinus carpio",
    family: "Cyprinidae",
  },
  {
    id: 40,
    speciesName: "Esox lucius",
    germanName: "Hecht",
    latinName: "Esox lucius",
    family: "Esocidae",
  },
  {
    id: 41,
    speciesName: "Eudontomyzon mariae",
    germanName: "Ukrainisches Neunauge",
    latinName: "Eudontomyzon mariae",
    family: "Petromyzontidae",
  },
  {
    id: 42,
    speciesName: "Gasterosteus aculeatus",
    germanName: "Dreistachliger Stichling",
    latinName: "Gasterosteus aculeatus",
    family: "Gasterosteidae",
  },
  {
    id: 43,
    speciesName: "Gobio gobio",
    germanName: "Gründling",
    latinName: "Gobio gobio",
    family: "Cyprinidae",
  },
  {
    id: 44,
    speciesName: "Gobio obtusirostris",
    germanName: "Donautalgründling",
    latinName: "Gobio obtusirostris",
    family: "Cyprinidae",
  },
  {
    id: 45,
    speciesName: "Gobio/Romanogobio sp.",
    germanName: "Gründling sp.",
    latinName: "Gobio/Romanogobio sp.",
    family: "Cyprinidae",
  },
  {
    id: 46,
    speciesName: "Gymnocephalus baloni",
    germanName: "Donaukaulbarsch",
    latinName: "Gymnocephalus baloni",
    family: "Percidae",
  },
  {
    id: 47,
    speciesName: "Gymnocephalus cernua",
    germanName: "Kaulbarsch",
    latinName: "Gymnocephalus cernua",
    family: "Percidae",
  },
  {
    id: 48,
    speciesName: "Gymnocephalus schraetser",
    germanName: "Schrätzer",
    latinName: "Gymnocephalus schraetser",
    family: "Percidae",
  },
  {
    id: 49,
    speciesName: "Hucho hucho",
    germanName: "Huchen",
    latinName: "Hucho hucho",
    family: "Salmonidae",
  },
  {
    id: 50,
    speciesName: "Huso huso",
    germanName: "Hausen (Beluga-Stör)",
    latinName: "Huso huso",
    family: "Acipenseridae",
  },
  {
    id: 51,
    speciesName: "Hypophthalmichthys molitrix",
    germanName: "Silberkarpfen",
    latinName: "Hypophthalmichthys molitrix",
    family: "Cyprinidae",
  },
  {
    id: 52,
    speciesName: "Hypophthalmichthys nobilis",
    germanName: "Marmorkarpfen",
    latinName: "Hypophthalmichthys nobilis",
    family: "Cyprinidae",
  },
  {
    id: 53,
    speciesName: "Hypophthalmichthys sp.",
    germanName: "Tolpyga sp.",
    latinName: "Hypophthalmichthys sp.",
    family: "Cyprinidae",
  },
  {
    id: 54,
    speciesName: "Ictalurus punctatus",
    germanName: "Getüpfelter Gabelwels",
    latinName: "Ictalurus punctatus",
    family: "Ictaluridae",
  },
  {
    id: 55,
    speciesName: "Lampetra planeri",
    germanName: "Bachneunauge",
    latinName: "Lampetra planeri",
    family: "Petromyzontidae",
  },
  {
    id: 56,
    speciesName: "Lepomis gibbosus",
    germanName: "Sonnenbarsch",
    latinName: "Lepomis gibbosus",
    family: "Centrarchidae",
  },
  {
    id: 57,
    speciesName: "Leucaspius delineatus",
    germanName: "Moderlieschen",
    latinName: "Leucaspius delineatus",
    family: "Cyprinidae",
  },
  {
    id: 58,
    speciesName: "Leuciscus aspius",
    germanName: "Schied (Rapfen)",
    latinName: "Leuciscus aspius",
    family: "Cyprinidae",
  },
  {
    id: 59,
    speciesName: "Leuciscus aspius hyb",
    germanName: "Schied-Hybrid",
    latinName: "Leuciscus aspius hyb",
    family: "Cyprinidae",
  },
  {
    id: 60,
    speciesName: "Leuciscus aspius/idus hyb",
    germanName: "Schied/Aland-Hybrid",
    latinName: "Leuciscus aspius/idus hyb",
    family: "Cyprinidae",
  },
  {
    id: 61,
    speciesName: "Leuciscus idus",
    germanName: "Aland (Orfe)",
    latinName: "Leuciscus idus",
    family: "Cyprinidae",
  },
  {
    id: 62,
    speciesName: "Leuciscus idus hybrid",
    germanName: "Aland-Hybrid",
    latinName: "Leuciscus idus hybrid",
    family: "Cyprinidae",
  },
  {
    id: 63,
    speciesName: "Leuciscus leuciscus",
    germanName: "Hasel",
    latinName: "Leuciscus leuciscus",
    family: "Cyprinidae",
  },
  {
    id: 64,
    speciesName: "Leuciscus sp.",
    germanName: "Leuciscus sp.",
    latinName: "Leuciscus sp.",
    family: "Cyprinidae",
  },
  {
    id: 65,
    speciesName: "Lota lota",
    germanName: "Quappe (Rutte)",
    latinName: "Lota lota",
    family: "Lotidae",
  },
  {
    id: 66,
    speciesName: "Micropterus salmoides",
    germanName: "Forellenbarsch",
    latinName: "Micropterus salmoides",
    family: "Centrarchidae",
  },
  {
    id: 67,
    speciesName: "Misgurnus bipartitus",
    germanName: "Schlammpeitzger sp.",
    latinName: "Misgurnus bipartitus",
    family: "Cobitidae",
  },
  {
    id: 68,
    speciesName: "Misgurnus fossilis",
    germanName: "Schlammpeitzger",
    latinName: "Misgurnus fossilis",
    family: "Cobitidae",
  },
  {
    id: 69,
    speciesName: "Neogobius fluviatilis",
    germanName: "Flussgrundel",
    latinName: "Neogobius fluviatilis",
    family: "Gobiidae",
  },
  {
    id: 70,
    speciesName: "Neogobius melanostomus",
    germanName: "Schwarzmundgrundel",
    latinName: "Neogobius melanostomus",
    family: "Gobiidae",
  },
  {
    id: 71,
    speciesName: "Neogobius sp.",
    germanName: "Neogobius sp.",
    latinName: "Neogobius sp.",
    family: "Gobiidae",
  },
  {
    id: 72,
    speciesName: "Nicht Beprobbar",
    germanName: "Nicht beprobbar",
    latinName: "Nicht Beprobbar",
    family: "",
  },
  {
    id: 73,
    speciesName: "no catch",
    germanName: "Kein Fang",
    latinName: "no catch",
    family: "",
  },
  {
    id: 74,
    speciesName: "Oncorhynchus kisutch",
    germanName: "Coho-Lachs",
    latinName: "Oncorhynchus kisutch",
    family: "Salmonidae",
  },
  {
    id: 75,
    speciesName: "Oncorhynchus mykiss",
    germanName: "Regenbogenforelle",
    latinName: "Oncorhynchus mykiss",
    family: "Salmonidae",
  },
  {
    id: 76,
    speciesName: "Pelecus cultratus",
    germanName: "Sichling",
    latinName: "Pelecus cultratus",
    family: "Cyprinidae",
  },
  {
    id: 77,
    speciesName: "Perca fluviatilis",
    germanName: "Flussbarsch",
    latinName: "Perca fluviatilis",
    family: "Percidae",
  },
  {
    id: 78,
    speciesName: "Phoxinus phoxinus",
    germanName: "Elritze",
    latinName: "Phoxinus phoxinus",
    family: "Cyprinidae",
  },
  {
    id: 79,
    speciesName: "Ponticola kessleri",
    germanName: "Kessler-Grundel",
    latinName: "Ponticola kessleri",
    family: "Gobiidae",
  },
  {
    id: 80,
    speciesName: "Proterorhinus semilunaris",
    germanName: "Marmorgrundel",
    latinName: "Proterorhinus semilunaris",
    family: "Gobiidae",
  },
  {
    id: 81,
    speciesName: "Pseudorasbora parva",
    germanName: "Blaubandbärbling",
    latinName: "Pseudorasbora parva",
    family: "Cyprinidae",
  },
  {
    id: 82,
    speciesName: "Pungitius pungitius",
    germanName: "Zwergstichling",
    latinName: "Pungitius pungitius",
    family: "Gasterosteidae",
  },
  {
    id: 83,
    speciesName: "Rhodeus amarus",
    germanName: "Bitterling",
    latinName: "Rhodeus amarus",
    family: "Cyprinidae",
  },
  {
    id: 84,
    speciesName: "Romanogobio carpathorossicus",
    germanName: "Karpatengrundel",
    latinName: "Romanogobio carpathorossicus",
    family: "Cyprinidae",
  },
  {
    id: 85,
    speciesName: "Romanogobio kesslerii",
    germanName: "Kesslerscher Gründling",
    latinName: "Romanogobio kesslerii",
    family: "Cyprinidae",
  },
  {
    id: 86,
    speciesName: "Romanogobio skywalkeri",
    germanName: "Skywalker-Grundel",
    latinName: "Romanogobio skywalkeri",
    family: "Cyprinidae",
  },
  {
    id: 87,
    speciesName: "Romanogobio sp.",
    germanName: "Romanogobio sp.",
    latinName: "Romanogobio sp.",
    family: "Cyprinidae",
  },
  {
    id: 88,
    speciesName: "Romanogobio uranoscopus",
    germanName: "Steingrundel",
    latinName: "Romanogobio uranoscopus",
    family: "Cyprinidae",
  },
  {
    id: 89,
    speciesName: "Romanogobio vladykovi",
    germanName: "Vladykov-Grundel",
    latinName: "Romanogobio vladykovi",
    family: "Cyprinidae",
  },
  {
    id: 90,
    speciesName: "Rutilus hybrid",
    germanName: "Rotauge-Hybrid",
    latinName: "Rutilus hybrid",
    family: "Cyprinidae",
  },
  {
    id: 91,
    speciesName: "Rutilus meidingeri",
    germanName: "Perlfisch",
    latinName: "Rutilus meidingeri",
    family: "Cyprinidae",
  },
  {
    id: 92,
    speciesName: "Rutilus rutilus",
    germanName: "Rotauge",
    latinName: "Rutilus rutilus",
    family: "Cyprinidae",
  },
  {
    id: 93,
    speciesName: "Rutilus rutilus hyb",
    germanName: "Rotauge-Hybrid",
    latinName: "Rutilus rutilus hyb",
    family: "Cyprinidae",
  },
  {
    id: 94,
    speciesName: "Rutilus rutilus hybrid",
    germanName: "Rotauge-Hybrid",
    latinName: "Rutilus rutilus hybrid",
    family: "Cyprinidae",
  },
  {
    id: 95,
    speciesName: "Rutilus rutilus x Abramis brama",
    germanName: "Rotauge x Brachse",
    latinName: "Rutilus rutilus x Abramis brama",
    family: "Cyprinidae",
  },
  {
    id: 96,
    speciesName: "Rutilus rutilus x Rutilus virgo",
    germanName: "Rotauge x Perlfisch-Hybrid",
    latinName: "Rutilus rutilus x Rutilus virgo",
    family: "Cyprinidae",
  },
  {
    id: 97,
    speciesName: "Rutilus rutilus x Scardinus erythrophthalamus (hybrid)",
    germanName: "Rotauge x Rotfeder-Hybrid",
    latinName: "Rutilus rutilus x Scardinus erythrophthalamus (hybrid)",
    family: "Cyprinidae",
  },
  {
    id: 98,
    speciesName: "Rutilus virgo",
    germanName: "Frauennerfling",
    latinName: "Rutilus virgo",
    family: "Cyprinidae",
  },
  {
    id: 99,
    speciesName: "Rutilus virgo hybrid",
    germanName: "Frauennerfling-Hybrid",
    latinName: "Rutilus virgo hybrid",
    family: "Cyprinidae",
  },
  {
    id: 100,
    speciesName: "Rutilus virgo x Rutilus rutilus",
    germanName: "Frauennerfling x Rotauge",
    latinName: "Rutilus virgo x Rutilus rutilus",
    family: "Cyprinidae",
  },
  {
    id: 101,
    speciesName: "Sabanejewia balcanica",
    germanName: "Balkan-Dorngrundel",
    latinName: "Sabanejewia balcanica",
    family: "Cobitidae",
  },
  {
    id: 102,
    speciesName: "Salmo trutta",
    germanName: "Bachforelle",
    latinName: "Salmo trutta",
    family: "Salmonidae",
  },
  {
    id: 103,
    speciesName: "Salmo trutta x Salvelinus fontinalis",
    germanName: "Bachforelle x Bachsaibling",
    latinName: "Salmo trutta x Salvelinus fontinalis",
    family: "Salmonidae",
  },
  {
    id: 104,
    speciesName: "Salmonidae",
    germanName: "Lachsfisch",
    latinName: "Salmonidae",
    family: "Salmonidae",
  },
  {
    id: 105,
    speciesName: "Salvelinus fontinalis",
    germanName: "Bachsaibling",
    latinName: "Salvelinus fontinalis",
    family: "Salmonidae",
  },
  {
    id: 106,
    speciesName: "Salvelinus fontinalis × Salvelinus umbla",
    germanName: "Saibling-Hybrid",
    latinName: "Salvelinus fontinalis × Salvelinus umbla",
    family: "Salmonidae",
  },
  {
    id: 107,
    speciesName: "Salvelinus namaycush",
    germanName: "Amerikanischer Seesaibling",
    latinName: "Salvelinus namaycush",
    family: "Salmonidae",
  },
  {
    id: 108,
    speciesName: "Salvelinus sp.",
    germanName: "Saibling sp.",
    latinName: "Salvelinus sp.",
    family: "Salmonidae",
  },
  {
    id: 109,
    speciesName: "Salvelinus umbla",
    germanName: "Seesaibling",
    latinName: "Salvelinus umbla",
    family: "Salmonidae",
  },
  {
    id: 110,
    speciesName: "Sander lucioperca",
    germanName: "Zander",
    latinName: "Sander lucioperca",
    family: "Percidae",
  },
  {
    id: 111,
    speciesName: "Sander volgensis",
    germanName: "Wolgazander",
    latinName: "Sander volgensis",
    family: "Percidae",
  },
  {
    id: 112,
    speciesName: "Scardinius erythrophthalmus",
    germanName: "Rotfeder",
    latinName: "Scardinius erythrophthalmus",
    family: "Cyprinidae",
  },
  {
    id: 113,
    speciesName: "Silurus glanis",
    germanName: "Wels",
    latinName: "Silurus glanis",
    family: "Siluridae",
  },
  {
    id: 114,
    speciesName: "Squalius cephalus",
    germanName: "Döbel (Aitel)",
    latinName: "Squalius cephalus",
    family: "Cyprinidae",
  },
  {
    id: 115,
    speciesName: "Squalius cephalus x Alburnus mento",
    germanName: "Döbel x Seelaube",
    latinName: "Squalius cephalus x Alburnus mento",
    family: "Cyprinidae",
  },
  {
    id: 116,
    speciesName: "Telestes souffia",
    germanName: "Strömer",
    latinName: "Telestes souffia",
    family: "Cyprinidae",
  },
  {
    id: 117,
    speciesName: "Thymallus thymallus",
    germanName: "Äsche",
    latinName: "Thymallus thymallus",
    family: "Thymallidae",
  },
  {
    id: 118,
    speciesName: "Tinca tinca",
    germanName: "Schleie",
    latinName: "Tinca tinca",
    family: "Cyprinidae",
  },
  {
    id: 119,
    speciesName: "Umbra krameri",
    germanName: "Hundsfisch",
    latinName: "Umbra krameri",
    family: "Umbridae",
  },
  {
    id: 120,
    speciesName: "Vimba vimba",
    germanName: "Zährte",
    latinName: "Vimba vimba",
    family: "Cyprinidae",
  },
  {
    id: 121,
    speciesName: "Vimba vimba hybrid",
    germanName: "Zährte-Hybrid",
    latinName: "Vimba vimba hybrid",
    family: "Cyprinidae",
  },
  {
    id: 122,
    speciesName: "Vimba x Blicca",
    germanName: "Zährte x Güster",
    latinName: "Vimba x Blicca",
    family: "Cyprinidae",
  },
  {
    id: 123,
    speciesName: "Zingel streber",
    germanName: "Streber",
    latinName: "Zingel streber",
    family: "Percidae",
  },
  {
    id: 124,
    speciesName: "Zingel zingel",
    germanName: "Zingel",
    latinName: "Zingel zingel",
    family: "Percidae",
  },
  {
    id: 125,
    speciesName: "unknown",
    germanName: "Unbekannt",
    latinName: "unknown",
    family: "",
  },
];

async function main() {
  for (const s of SPECIES) {
    await prisma.fishSpecies.upsert({
      where: { id: s.id },
      update: {
        speciesName: s.speciesName,
        germanName: s.germanName,
        latinName: s.latinName,
        family: s.family,
      },
      create: {
        id: s.id,
        speciesName: s.speciesName,
        germanName: s.germanName,
        latinName: s.latinName,
        family: s.family,
      },
    });
  }

  console.log(`✅ Insert/Update completed for ${SPECIES.length} species.`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
