import { prisma } from "@/lib/prisma";

type SamplingRow = {
  id: number;
  siteId: number;
  year: number;
  catchDate?: Date;
  dataProvider?: string;
  askProviderBeforeUse?: boolean;
  source?: string;
  project?: string;
  fishingAuthority?: string;
  preclassificationStressor?: string;
  temp?: number;
  conductivity?: number;
  pHValue?: number;
  oCont?: number;
  oSat?: number;
  method?: string;
  assessment?: string;
  samplingStrategy?: string;
  anodes?: number;
  numSubsections?: number;
  lengthSubsection?: number;
  widthSubsection?: number;
  typeOfStrip?: string;
  habitat?: string;
  runStrip?: string;
  catchEfficiency?: number;
  remarksRawData?: string;
  remarkImport?: string;
};

const SAMPLINGS: SamplingRow[] = [
  {
    id: 1,
    siteId: 1, // Donau Wien
    year: 2023,
    catchDate: new Date("2023-05-15"),
    dataProvider: "Michael Grohmann",
    askProviderBeforeUse: true,
    source: "IHG",
    project: "Donau Monitoring",
    fishingAuthority: "Wiener Gewässer Management",
    preclassificationStressor: "Urban pollution",
    temp: 18.5,
    conductivity: 420,
    pHValue: 8.1,
    oCont: 9.2,
    oSat: 92,
    method: "Boat",
    assessment: "strip",
    samplingStrategy: "partialprop",
    anodes: 2,
    numSubsections: 5,
    lengthSubsection: 100.0,
    widthSubsection: 15.0,
    typeOfStrip: "Längsstreifen",
    habitat: "Hauptstrom",
    runStrip: "Fließend",
    catchEfficiency: 85.0,
    remarksRawData: "Hoher Schiffsverkehr",
    remarkImport: "Daten vollständig",
  },
  {
    id: 2,
    siteId: 2, // Donau Krems
    year: 2023,
    catchDate: new Date("2023-06-10"),
    dataProvider: "Anna Müller",
    askProviderBeforeUse: false,
    source: "IHG",
    project: "Donau Monitoring",
    fishingAuthority: "NÖ Landesfischerei",
    preclassificationStressor: "Shipping traffic",
    temp: 20.2,
    conductivity: 380,
    pHValue: 7.9,
    oCont: 8.8,
    oSat: 88,
    method: "Wading",
    assessment: "point",
    samplingStrategy: "representative",
    anodes: 1,
    numSubsections: 3,
    lengthSubsection: 50.0,
    widthSubsection: 20.0,
    typeOfStrip: "Querstreifen",
    habitat: "Uferbereich",
    runStrip: "Pool",
    catchEfficiency: 78.0,
    remarksRawData: "Klares Wasser",
    remarkImport: "Alle Parameter erfasst",
  },
  {
    id: 3,
    siteId: 3, // Inn Innsbruck
    year: 2023,
    catchDate: new Date("2023-07-22"),
    dataProvider: "Thomas Fischer",
    askProviderBeforeUse: true,
    source: "Universität Innsbruck",
    project: "Alpenflüsse Studie",
    fishingAuthority: "Tiroler Fischereiverband",
    preclassificationStressor: "Hydropeaking",
    temp: 15.8,
    conductivity: 280,
    pHValue: 8.3,
    oCont: 10.5,
    oSat: 95,
    method: "Wading",
    assessment: "strip",
    samplingStrategy: "systematic",
    anodes: 1,
    numSubsections: 4,
    lengthSubsection: 62.5,
    widthSubsection: 8.0,
    typeOfStrip: "Längsstreifen",
    habitat: "Riesel",
    runStrip: "Schnellfließend",
    catchEfficiency: 82.0,
    remarksRawData: "Starke Strömung",
    remarkImport: "Gute Datenlage",
  },
  {
    id: 4,
    siteId: 4, // Enns Steyr
    year: 2023,
    catchDate: new Date("2023-08-05"),
    dataProvider: "Lisa Weber",
    askProviderBeforeUse: false,
    source: "BOKU Wien",
    project: "Enns Ökologie",
    fishingAuthority: "OÖ Landesfischerei",
    preclassificationStressor: "Industrial discharge",
    temp: 19.7,
    conductivity: 320,
    pHValue: 7.8,
    oCont: 9.1,
    oSat: 89,
    method: "Boat",
    assessment: "point",
    samplingStrategy: "random",
    anodes: 2,
    numSubsections: 3,
    lengthSubsection: 60.0,
    widthSubsection: 12.0,
    typeOfStrip: "Querstreifen",
    habitat: "Tiefwasser",
    runStrip: "Pool",
    catchEfficiency: 75.0,
    remarksRawData: "Trübes Wasser nach Regen",
    remarkImport: "Vollständige Aufnahme",
  },
  {
    id: 5,
    siteId: 5, // Salzach Salzburg
    year: 2023,
    catchDate: new Date("2023-09-12"),
    dataProvider: "Peter Huber",
    askProviderBeforeUse: true,
    source: "Land Salzburg",
    project: "Salzach Monitoring",
    fishingAuthority: "Salzburger Fischereiverein",
    preclassificationStressor: "Urban runoff",
    temp: 16.3,
    conductivity: 250,
    pHValue: 8.0,
    oCont: 9.8,
    oSat: 93,
    method: "Wading",
    assessment: "strip",
    samplingStrategy: "partialprop",
    anodes: 1,
    numSubsections: 4,
    lengthSubsection: 50.0,
    widthSubsection: 10.0,
    typeOfStrip: "Längsstreifen",
    habitat: "Kiesbett",
    runStrip: "Fließend",
    catchEfficiency: 88.0,
    remarksRawData: "Optimale Bedingungen",
    remarkImport: "Alle Daten plausibel",
  },
  {
    id: 6,
    siteId: 6, // Traun Gmunden
    year: 2024,
    catchDate: new Date("2024-04-18"),
    dataProvider: "Maria Schmidt",
    askProviderBeforeUse: false,
    source: "IHG",
    project: "Traun Bestandserhebung",
    fishingAuthority: "OÖ Landesfischerei",
    preclassificationStressor: "Lake discharge",
    temp: 12.8,
    conductivity: 180,
    pHValue: 7.6,
    oCont: 11.2,
    oSat: 98,
    method: "Wading",
    assessment: "point",
    samplingStrategy: "representative",
    anodes: 1,
    numSubsections: 2,
    lengthSubsection: 75.0,
    widthSubsection: 6.0,
    typeOfStrip: "Querstreifen",
    habitat: "Uferzone",
    runStrip: "Langsam fließend",
    catchEfficiency: 90.0,
    remarksRawData: "Sehr klares Wasser",
    remarkImport: "Hervorragende Sicht",
  },
  {
    id: 7,
    siteId: 7, // Kamp Zwettl
    year: 2024,
    catchDate: new Date("2024-05-20"),
    dataProvider: "Johann Bauer",
    askProviderBeforeUse: true,
    source: "NÖ Landesregierung",
    project: "Kleingewässer Monitoring",
    fishingAuthority: "Waldviertler Fischereiverein",
    preclassificationStressor: "Agricultural runoff",
    temp: 14.5,
    conductivity: 220,
    pHValue: 7.4,
    oCont: 10.8,
    oSat: 96,
    method: "Wading",
    assessment: "strip",
    samplingStrategy: "systematic",
    anodes: 1,
    numSubsections: 3,
    lengthSubsection: 40.0,
    widthSubsection: 4.0,
    typeOfStrip: "Längsstreifen",
    habitat: "Flachufer",
    runStrip: "Riesel",
    catchEfficiency: 85.0,
    remarksRawData: "Niederwasser",
    remarkImport: "Standardbefischung",
  },
  {
    id: 8,
    siteId: 8, // Mur Graz
    year: 2024,
    catchDate: new Date("2024-06-15"),
    dataProvider: "Sandra Kaufmann",
    askProviderBeforeUse: false,
    source: "Universität Graz",
    project: "Mur Ökosystem",
    fishingAuthority: "Steirischer Fischereiverband",
    preclassificationStressor: "Urban pollution",
    temp: 21.2,
    conductivity: 380,
    pHValue: 8.2,
    oCont: 8.5,
    oSat: 85,
    method: "Boat",
    assessment: "point",
    samplingStrategy: "random",
    anodes: 2,
    numSubsections: 4,
    lengthSubsection: 70.0,
    widthSubsection: 14.0,
    typeOfStrip: "Querstreifen",
    habitat: "Hauptstrom",
    runStrip: "Pool",
    catchEfficiency: 72.0,
    remarksRawData: "Sommerhitze",
    remarkImport: "Typische Sommerwerte",
  },
  {
    id: 9,
    siteId: 9, // Pielach Loosdorf
    year: 2024,
    catchDate: new Date("2024-07-08"),
    dataProvider: "Robert Steiner",
    askProviderBeforeUse: true,
    source: "BOKU Wien",
    project: "Nebenflüsse Donau",
    fishingAuthority: "NÖ Landesfischerei",
    preclassificationStressor: "None identified",
    temp: 17.9,
    conductivity: 300,
    pHValue: 7.7,
    oCont: 9.5,
    oSat: 91,
    method: "Wading",
    assessment: "strip",
    samplingStrategy: "partialprop",
    anodes: 1,
    numSubsections: 2,
    lengthSubsection: 50.0,
    widthSubsection: 3.5,
    typeOfStrip: "Längsstreifen",
    habitat: "Kiesbank",
    runStrip: "Schnellfließend",
    catchEfficiency: 87.0,
    remarksRawData: "Naturnaher Zustand",
    remarkImport: "Referenzgewässer",
  },
  {
    id: 10,
    siteId: 10, // Ybbs Amstetten
    year: 2024,
    catchDate: new Date("2024-08-25"),
    dataProvider: "Christina Hofer",
    askProviderBeforeUse: false,
    source: "Land NÖ",
    project: "Ybbs Renaturierung",
    fishingAuthority: "Mostviertler Fischereiverein",
    preclassificationStressor: "Channel modification",
    temp: 19.1,
    conductivity: 340,
    pHValue: 7.9,
    oCont: 8.9,
    oSat: 87,
    method: "Wading",
    assessment: "point",
    samplingStrategy: "representative",
    anodes: 1,
    numSubsections: 3,
    lengthSubsection: 53.3,
    widthSubsection: 5.5,
    typeOfStrip: "Querstreifen",
    habitat: "Renaturiert",
    runStrip: "Variabel",
    catchEfficiency: 80.0,
    remarksRawData: "Renaturierungsmaßnahmen sichtbar",
    remarkImport: "Monitoring nach Renaturierung",
  },
];

async function main() {
  console.log("🎣 Inserting samplings...");

  await Promise.all(
    SAMPLINGS.map((sampling) =>
      prisma.sampling.upsert({
        where: { id: sampling.id },
        update: {
          siteId: sampling.siteId,
          year: sampling.year,
          catchDate: sampling.catchDate,
          dataProvider: sampling.dataProvider,
          askProviderBeforeUse: sampling.askProviderBeforeUse,
          source: sampling.source,
          project: sampling.project,
          fishingAuthority: sampling.fishingAuthority,
          preclassificationStressor: sampling.preclassificationStressor,
          temp: sampling.temp,
          conductivity: sampling.conductivity,
          pHValue: sampling.pHValue,
          oCont: sampling.oCont,
          oSat: sampling.oSat,
          method: sampling.method,
          assessment: sampling.assessment,
          samplingStrategy: sampling.samplingStrategy,
          anodes: sampling.anodes,
          numSubsections: sampling.numSubsections,
          lengthSubsection: sampling.lengthSubsection,
          widthSubsection: sampling.widthSubsection,
          typeOfStrip: sampling.typeOfStrip,
          habitat: sampling.habitat,
          runStrip: sampling.runStrip,
          catchEfficiency: sampling.catchEfficiency,
          remarksRawData: sampling.remarksRawData,
          remarkImport: sampling.remarkImport,
        },
        create: {
          id: sampling.id,
          siteId: sampling.siteId,
          year: sampling.year,
          catchDate: sampling.catchDate,
          dataProvider: sampling.dataProvider,
          askProviderBeforeUse: sampling.askProviderBeforeUse,
          source: sampling.source,
          project: sampling.project,
          fishingAuthority: sampling.fishingAuthority,
          preclassificationStressor: sampling.preclassificationStressor,
          temp: sampling.temp,
          conductivity: sampling.conductivity,
          pHValue: sampling.pHValue,
          oCont: sampling.oCont,
          oSat: sampling.oSat,
          method: sampling.method,
          assessment: sampling.assessment,
          samplingStrategy: sampling.samplingStrategy,
          anodes: sampling.anodes,
          numSubsections: sampling.numSubsections,
          lengthSubsection: sampling.lengthSubsection,
          widthSubsection: sampling.widthSubsection,
          typeOfStrip: sampling.typeOfStrip,
          habitat: sampling.habitat,
          runStrip: sampling.runStrip,
          catchEfficiency: sampling.catchEfficiency,
          remarksRawData: sampling.remarksRawData,
          remarkImport: sampling.remarkImport,
        },
      })
    )
  );

  console.log(`✅ Insert/Update completed for ${SAMPLINGS.length} samplings.`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
