name: Deploy CatchLogX

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Update repository
        run: |
          cd /opt/CatchLogX
          git fetch origin master
          git reset --hard origin/master

      - name: Deploy with Docker Compose
        run: |
          cd /opt/CatchLogX
          docker compose down
          docker compose up -d --build

      - name: Show running containers
        run: |
          docker ps
